# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1080, 690)
        widget.setMinimumSize(QtCore.QSize(1080, 690))
        widget.setMaximumSize(QtCore.QSize(1080, 690))
        self.groupBoxDisplay = QtWidgets.QGroupBox(widget)
        self.groupBoxDisplay.setGeometry(QtCore.QRect(10, 150, 1061, 231))
        self.groupBoxDisplay.setObjectName("groupBoxDisplay")
        self.widgetStatus = QtWidgets.QWidget(self.groupBoxDisplay)
        self.widgetStatus.setGeometry(QtCore.QRect(10, 10, 1041, 38))
        self.widgetStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetStatus.setObjectName("widgetStatus")
        self.labelStatus = QtWidgets.QLabel(self.widgetStatus)
        self.labelStatus.setGeometry(QtCore.QRect(9, 9, 41, 21))
        self.labelStatus.setObjectName("labelStatus")
        self.lineEditStatus = QtWidgets.QLineEdit(self.widgetStatus)
        self.lineEditStatus.setGeometry(QtCore.QRect(51, 10, 981, 20))
        self.lineEditStatus.setObjectName("lineEditStatus")
        self.widgetRegister = QtWidgets.QWidget(self.groupBoxDisplay)
        self.widgetRegister.setGeometry(QtCore.QRect(10, 40, 1041, 185))
        self.widgetRegister.setObjectName("widgetRegister")
        self.labelTaskResponseRegister = QtWidgets.QLabel(self.widgetRegister)
        self.labelTaskResponseRegister.setGeometry(QtCore.QRect(515, 9, 96, 16))
        self.labelTaskResponseRegister.setObjectName("labelTaskResponseRegister")
        self.labelTaskRegister = QtWidgets.QLabel(self.widgetRegister)
        self.labelTaskRegister.setGeometry(QtCore.QRect(9, 9, 72, 16))
        self.labelTaskRegister.setObjectName("labelTaskRegister")
        self.textEditTaskRespondRegister = QtWidgets.QTextEdit(self.widgetRegister)
        self.textEditTaskRespondRegister.setGeometry(QtCore.QRect(515, 27, 520, 150))
        self.textEditTaskRespondRegister.setMinimumSize(QtCore.QSize(520, 150))
        self.textEditTaskRespondRegister.setMaximumSize(QtCore.QSize(520, 150))
        self.textEditTaskRespondRegister.setObjectName("textEditTaskRespondRegister")
        self.textEditTaskRegister = QtWidgets.QTextEdit(self.widgetRegister)
        self.textEditTaskRegister.setGeometry(QtCore.QRect(9, 27, 500, 150))
        self.textEditTaskRegister.setMinimumSize(QtCore.QSize(500, 150))
        self.textEditTaskRegister.setMaximumSize(QtCore.QSize(500, 150))
        self.textEditTaskRegister.setObjectName("textEditTaskRegister")
        self.btnParseHeatMeterData = QtWidgets.QPushButton(widget)
        self.btnParseHeatMeterData.setGeometry(QtCore.QRect(440, 390, 121, 23))
        self.btnParseHeatMeterData.setObjectName("btnParseHeatMeterData")
        self.textEditParseHeatMeterData = QtWidgets.QTextEdit(widget)
        self.textEditParseHeatMeterData.setGeometry(QtCore.QRect(10, 420, 1061, 261))
        self.textEditParseHeatMeterData.setObjectName("textEditParseHeatMeterData")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(10, 390, 431, 21))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.btnCleanParseResult = QtWidgets.QPushButton(widget)
        self.btnCleanParseResult.setGeometry(QtCore.QRect(570, 390, 121, 23))
        self.btnCleanParseResult.setObjectName("btnCleanParseResult")
        self.groupBoxBMUMode = QtWidgets.QGroupBox(widget)
        self.groupBoxBMUMode.setGeometry(QtCore.QRect(490, 10, 581, 142))
        self.groupBoxBMUMode.setObjectName("groupBoxBMUMode")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxBMUMode)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSetBMUMode00 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode00.setObjectName("btnSetBMUMode00")
        self.gridLayout.addWidget(self.btnSetBMUMode00, 2, 0, 1, 1)
        self.btnSetBMUMode30 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode30.setObjectName("btnSetBMUMode30")
        self.gridLayout.addWidget(self.btnSetBMUMode30, 2, 7, 1, 2)
        self.btnSetBMUMode50 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode50.setObjectName("btnSetBMUMode50")
        self.gridLayout.addWidget(self.btnSetBMUMode50, 4, 1, 1, 2)
        self.btnSetBMUModeB0 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUModeB0.setObjectName("btnSetBMUModeB0")
        self.gridLayout.addWidget(self.btnSetBMUModeB0, 4, 7, 1, 2)
        self.btnSetBMUModeA0 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUModeA0.setObjectName("btnSetBMUModeA0")
        self.gridLayout.addWidget(self.btnSetBMUModeA0, 3, 0, 1, 1)
        self.btnSetBMUMode61 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode61.setObjectName("btnSetBMUMode61")
        self.gridLayout.addWidget(self.btnSetBMUMode61, 4, 0, 1, 1)
        self.btnSetBMUMode51 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode51.setObjectName("btnSetBMUMode51")
        self.gridLayout.addWidget(self.btnSetBMUMode51, 4, 4, 1, 1)
        self.btnReadBMUMode = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnReadBMUMode.setObjectName("btnReadBMUMode")
        self.gridLayout.addWidget(self.btnReadBMUMode, 0, 0, 1, 1)
        self.btnSetBMUMode40 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode40.setObjectName("btnSetBMUMode40")
        self.gridLayout.addWidget(self.btnSetBMUMode40, 3, 7, 1, 2)
        self.btnSetBMUModeA1 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUModeA1.setObjectName("btnSetBMUModeA1")
        self.gridLayout.addWidget(self.btnSetBMUModeA1, 3, 4, 1, 1)
        self.btnSetBMUMode20 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode20.setObjectName("btnSetBMUMode20")
        self.gridLayout.addWidget(self.btnSetBMUMode20, 0, 1, 1, 2)
        self.btnSetBMUMode21 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode21.setObjectName("btnSetBMUMode21")
        self.gridLayout.addWidget(self.btnSetBMUMode21, 0, 4, 1, 1)
        self.btnSetBMUMode22 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode22.setObjectName("btnSetBMUMode22")
        self.gridLayout.addWidget(self.btnSetBMUMode22, 0, 7, 1, 2)
        self.btnSetBMUModeA2 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUModeA2.setObjectName("btnSetBMUModeA2")
        self.gridLayout.addWidget(self.btnSetBMUModeA2, 2, 4, 1, 1)
        self.btnSetBMUMode11 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode11.setObjectName("btnSetBMUMode11")
        self.gridLayout.addWidget(self.btnSetBMUMode11, 3, 1, 1, 2)
        self.btnSetBMUMode10 = QtWidgets.QPushButton(self.groupBoxBMUMode)
        self.btnSetBMUMode10.setObjectName("btnSetBMUMode10")
        self.gridLayout.addWidget(self.btnSetBMUMode10, 2, 1, 1, 2)
        self.groupBoxBaseFunc = QtWidgets.QGroupBox(widget)
        self.groupBoxBaseFunc.setGeometry(QtCore.QRect(10, 10, 461, 141))
        self.groupBoxBaseFunc.setObjectName("groupBoxBaseFunc")
        self.widgetBMUId = QtWidgets.QWidget(self.groupBoxBaseFunc)
        self.widgetBMUId.setGeometry(QtCore.QRect(10, 10, 300, 41))
        self.widgetBMUId.setMinimumSize(QtCore.QSize(300, 0))
        self.widgetBMUId.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widgetBMUId.setObjectName("widgetBMUId")
        self.labeBMUId = QtWidgets.QLabel(self.widgetBMUId)
        self.labeBMUId.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.labeBMUId.setMinimumSize(QtCore.QSize(0, 0))
        self.labeBMUId.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labeBMUId.setObjectName("labeBMUId")
        self.lineEditBMUId = QtWidgets.QLineEdit(self.widgetBMUId)
        self.lineEditBMUId.setGeometry(QtCore.QRect(70, 10, 125, 20))
        self.lineEditBMUId.setMinimumSize(QtCore.QSize(125, 0))
        self.lineEditBMUId.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lineEditBMUId.setObjectName("lineEditBMUId")
        self.btnRecoverBMUId = QtWidgets.QPushButton(self.widgetBMUId)
        self.btnRecoverBMUId.setGeometry(QtCore.QRect(251, 9, 40, 23))
        self.btnRecoverBMUId.setMinimumSize(QtCore.QSize(40, 0))
        self.btnRecoverBMUId.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnRecoverBMUId.setObjectName("btnRecoverBMUId")
        self.btnSetBMUId = QtWidgets.QPushButton(self.widgetBMUId)
        self.btnSetBMUId.setGeometry(QtCore.QRect(205, 9, 40, 23))
        self.btnSetBMUId.setMinimumSize(QtCore.QSize(0, 0))
        self.btnSetBMUId.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnSetBMUId.setObjectName("btnSetBMUId")
        self.widgetSetValveByID = QtWidgets.QWidget(self.groupBoxBaseFunc)
        self.widgetSetValveByID.setGeometry(QtCore.QRect(10, 70, 300, 41))
        self.widgetSetValveByID.setMinimumSize(QtCore.QSize(300, 0))
        self.widgetSetValveByID.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widgetSetValveByID.setObjectName("widgetSetValveByID")
        self.labeltValveId = QtWidgets.QLabel(self.widgetSetValveByID)
        self.labeltValveId.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.labeltValveId.setMinimumSize(QtCore.QSize(0, 0))
        self.labeltValveId.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labeltValveId.setObjectName("labeltValveId")
        self.lineEditValveId = QtWidgets.QLineEdit(self.widgetSetValveByID)
        self.lineEditValveId.setGeometry(QtCore.QRect(70, 10, 125, 20))
        self.lineEditValveId.setMinimumSize(QtCore.QSize(125, 0))
        self.lineEditValveId.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lineEditValveId.setObjectName("lineEditValveId")
        self.btnSetValveCloseById = QtWidgets.QPushButton(self.widgetSetValveByID)
        self.btnSetValveCloseById.setGeometry(QtCore.QRect(205, 9, 40, 23))
        self.btnSetValveCloseById.setMinimumSize(QtCore.QSize(40, 0))
        self.btnSetValveCloseById.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnSetValveCloseById.setObjectName("btnSetValveCloseById")
        self.btnSetValveOpenById = QtWidgets.QPushButton(self.widgetSetValveByID)
        self.btnSetValveOpenById.setGeometry(QtCore.QRect(251, 9, 40, 23))
        self.btnSetValveOpenById.setMinimumSize(QtCore.QSize(40, 0))
        self.btnSetValveOpenById.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnSetValveOpenById.setObjectName("btnSetValveOpenById")
        self.widgetReadHeatMeterDataByID = QtWidgets.QWidget(self.groupBoxBaseFunc)
        self.widgetReadHeatMeterDataByID.setGeometry(QtCore.QRect(10, 100, 300, 41))
        self.widgetReadHeatMeterDataByID.setMinimumSize(QtCore.QSize(300, 0))
        self.widgetReadHeatMeterDataByID.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widgetReadHeatMeterDataByID.setObjectName("widgetReadHeatMeterDataByID")
        self.labeltHeatMeterId = QtWidgets.QLabel(self.widgetReadHeatMeterDataByID)
        self.labeltHeatMeterId.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.labeltHeatMeterId.setMinimumSize(QtCore.QSize(0, 0))
        self.labeltHeatMeterId.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labeltHeatMeterId.setObjectName("labeltHeatMeterId")
        self.lineEditHeatMeterId = QtWidgets.QLineEdit(self.widgetReadHeatMeterDataByID)
        self.lineEditHeatMeterId.setGeometry(QtCore.QRect(70, 10, 125, 20))
        self.lineEditHeatMeterId.setMinimumSize(QtCore.QSize(125, 0))
        self.lineEditHeatMeterId.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lineEditHeatMeterId.setObjectName("lineEditHeatMeterId")
        self.btnReadHeatMeterDataByID = QtWidgets.QPushButton(self.widgetReadHeatMeterDataByID)
        self.btnReadHeatMeterDataByID.setGeometry(QtCore.QRect(200, 9, 91, 23))
        self.btnReadHeatMeterDataByID.setMinimumSize(QtCore.QSize(0, 0))
        self.btnReadHeatMeterDataByID.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnReadHeatMeterDataByID.setObjectName("btnReadHeatMeterDataByID")
        self.btnCleanTask = QtWidgets.QPushButton(self.groupBoxBaseFunc)
        self.btnCleanTask.setGeometry(QtCore.QRect(320, 20, 131, 23))
        self.btnCleanTask.setObjectName("btnCleanTask")
        self.btnReadHeatMeterData = QtWidgets.QPushButton(self.groupBoxBaseFunc)
        self.btnReadHeatMeterData.setGeometry(QtCore.QRect(320, 50, 131, 23))
        self.btnReadHeatMeterData.setObjectName("btnReadHeatMeterData")
        self.btnReadValveData = QtWidgets.QPushButton(self.groupBoxBaseFunc)
        self.btnReadValveData.setGeometry(QtCore.QRect(320, 80, 131, 23))
        self.btnReadValveData.setObjectName("btnReadValveData")
        self.btnElectricMeterData = QtWidgets.QPushButton(self.groupBoxBaseFunc)
        self.btnElectricMeterData.setGeometry(QtCore.QRect(320, 110, 131, 23))
        self.btnElectricMeterData.setObjectName("btnElectricMeterData")
        self.widgetCreateTable = QtWidgets.QWidget(self.groupBoxBaseFunc)
        self.widgetCreateTable.setGeometry(QtCore.QRect(10, 40, 300, 41))
        self.widgetCreateTable.setMinimumSize(QtCore.QSize(300, 0))
        self.widgetCreateTable.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widgetCreateTable.setObjectName("widgetCreateTable")
        self.labeCreateBMUId = QtWidgets.QLabel(self.widgetCreateTable)
        self.labeCreateBMUId.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.labeCreateBMUId.setMinimumSize(QtCore.QSize(0, 0))
        self.labeCreateBMUId.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labeCreateBMUId.setObjectName("labeCreateBMUId")
        self.lineEditCreateBMUId = QtWidgets.QLineEdit(self.widgetCreateTable)
        self.lineEditCreateBMUId.setGeometry(QtCore.QRect(70, 10, 125, 20))
        self.lineEditCreateBMUId.setMinimumSize(QtCore.QSize(125, 0))
        self.lineEditCreateBMUId.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lineEditCreateBMUId.setObjectName("lineEditCreateBMUId")
        self.btnDelTable = QtWidgets.QPushButton(self.widgetCreateTable)
        self.btnDelTable.setEnabled(True)
        self.btnDelTable.setGeometry(QtCore.QRect(251, 9, 40, 23))
        self.btnDelTable.setMinimumSize(QtCore.QSize(40, 0))
        self.btnDelTable.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnDelTable.setObjectName("btnDelTable")
        self.btnCreateTable = QtWidgets.QPushButton(self.widgetCreateTable)
        self.btnCreateTable.setGeometry(QtCore.QRect(205, 9, 40, 23))
        self.btnCreateTable.setMinimumSize(QtCore.QSize(0, 0))
        self.btnCreateTable.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnCreateTable.setObjectName("btnCreateTable")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "远程集中抄表系统控制程序"))
        self.groupBoxDisplay.setTitle(_translate("widget", "显示"))
        self.labelStatus.setText(_translate("widget", "状态："))
        self.labelTaskResponseRegister.setText(_translate("widget", "任务响应寄存器："))
        self.labelTaskRegister.setText(_translate("widget", "任务寄存器："))
        self.btnParseHeatMeterData.setText(_translate("widget", "解析热量表数据"))
        self.label.setText(_translate("widget", "在此输入需要解析的热量表数据报文，无输入数据则采用任务响应寄存器的数据："))
        self.btnCleanParseResult.setText(_translate("widget", "清除"))
        self.groupBoxBMUMode.setTitle(_translate("widget", "BMU模式"))
        self.btnSetBMUMode00.setText(_translate("widget", "值守模式"))
        self.btnSetBMUMode30.setText(_translate("widget", "用户档案下发模式"))
        self.btnSetBMUMode50.setText(_translate("widget", "广播升级模式"))
        self.btnSetBMUModeB0.setText(_translate("widget", "自动发现模式"))
        self.btnSetBMUModeA0.setText(_translate("widget", "连续自动抄收抄收模式"))
        self.btnSetBMUMode61.setText(_translate("widget", "初始化DTU模式"))
        self.btnSetBMUMode51.setText(_translate("widget", "依次升级模式"))
        self.btnReadBMUMode.setText(_translate("widget", "读取BMU工作模式"))
        self.btnSetBMUMode40.setText(_translate("widget", "设备状态下发模式"))
        self.btnSetBMUModeA1.setText(_translate("widget", "1轮3次整点自动抄收模式"))
        self.btnSetBMUMode20.setText(_translate("widget", "自校时模式"))
        self.btnSetBMUMode21.setText(_translate("widget", "广播校时模式"))
        self.btnSetBMUMode22.setText(_translate("widget", "依次校时模式"))
        self.btnSetBMUModeA2.setText(_translate("widget", "3轮1次整点自动抄收模式"))
        self.btnSetBMUMode11.setText(_translate("widget", "3次抄收模式"))
        self.btnSetBMUMode10.setText(_translate("widget", "1次抄收模式"))
        self.groupBoxBaseFunc.setTitle(_translate("widget", "基础功能"))
        self.labeBMUId.setText(_translate("widget", "BMU ID  ："))
        self.btnRecoverBMUId.setText(_translate("widget", "恢复"))
        self.btnSetBMUId.setText(_translate("widget", "修改"))
        self.labeltValveId.setText(_translate("widget", "阀门ID  ："))
        self.btnSetValveCloseById.setText(_translate("widget", "关"))
        self.btnSetValveOpenById.setText(_translate("widget", "开"))
        self.labeltHeatMeterId.setText(_translate("widget", "热量表ID："))
        self.btnReadHeatMeterDataByID.setText(_translate("widget", "读热量表数据"))
        self.btnCleanTask.setText(_translate("widget", "清空任务寄存器"))
        self.btnReadHeatMeterData.setText(_translate("widget", "读取服务器热量表数据"))
        self.btnReadValveData.setText(_translate("widget", "读取服务器智能阀数据"))
        self.btnElectricMeterData.setText(_translate("widget", "读取服务器电能表数据"))
        self.labeCreateBMUId.setText(_translate("widget", "BMU ID  ："))
        self.btnDelTable.setText(_translate("widget", "删表"))
        self.btnCreateTable.setText(_translate("widget", "建表"))


